PRESIDENT = 'PRESIDENT'
MEMBRE_BUREAU = 'MEMBRE_BUREAU'
DEPUTE = 'DEPUTE'
ANCIEN_PRESIDENT = 'ANCIEN_PRESIDENT'
DEPUTE_PRECEDENTE_LEGISLATURE = 'DEPUTE_PRECEDENTE_LEGISLATURE'

PROFILES_VALUES = {
    'PRESIDENT': PRESIDENT,
    'MEMBRE_BUREAU': MEMBRE_BUREAU,
    'DEPUTE': DEPUTE,
    'ANCIEN_PRESIDENT': ANCIEN_PRESIDENT,
    'DEPUTE_PRECEDENTE_LEGISLATURE': DEPUTE_PRECEDENTE_LEGISLATURE,
}

PROFILES = [
    (PRESIDENT, 'Président'),
    (MEMBRE_BUREAU, 'Membre du Bureau'),
    (DEPUTE, 'Député'),
    (ANCIEN_PRESIDENT, 'Ancien Président'),
    (DEPUTE_PRECEDENTE_LEGISLATURE, 'Député des précédentes législatures'),
]
