PRESIDENT = 'PRESIDENT'
MEMBRES_BUREAU = 'MEMBRES_BUREAU'
DEPUTE = 'DEPUTE'
ANCIENS_PRESIDENTS = 'ANCIENS_PRESIDENTS'
DEPUTES_PRECEDENTES_LEGISLATURES = 'DEPUTES_PRECEDENTES_LEGISLATURES'

PROFILES_VALUES = {
    'PRESIDENT': PRESIDENT,
    'MEMBRES_BUREAU': MEMBRES_BUREAU,
    'DEPUTE': DEPUTE,
    'ANCIENS_PRESIDENTS': ANCIENS_PRESIDENTS,
    'DEPUTES_PRECEDENTES_LEGISLATURES': DEPUTES_PRECEDENTES_LEGISLATURES,
}

PROFILES = [
    (PRESIDENT, 'Président'),
    (MEMBRES_BUREAU, 'Membres du Bureau'),
    (DEPUTE, 'Député'),
    (ANCIENS_PRESIDENTS, 'Anciens Présidents'),
    (DEPUTES_PRECEDENTES_LEGISLATURES, 'Députés des précédentes législatures'),
]
