# Generated by Django 4.2.1 on 2023-05-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name="Titre de l'actualite")),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActualiteImage',
            fields=[
                ('actualite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.actualite')),
                ('description', models.TextField(verbose_name="Description de l'actualite")),
            ],
            bases=('web.actualite',),
        ),
        migrations.CreateModel(
            name='ActualiteVideo',
            fields=[
                ('actualite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.actualite')),
                ('lien', models.CharField(max_length=255, verbose_name='Lien de la video')),
            ],
            bases=('web.actualite',),
        ),
    ]
