# Generated by Django 4.2.1 on 2023-05-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_actualite_actualiteimage_actualitevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAssociee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(blank=True, null=True, upload_to='actualites/images/')),
                ('actualiteImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.actualiteimage')),
            ],
        ),
    ]
