# Generated by Django 4.2.1 on 2023-05-17 04:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_imageassociee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualiteimage',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
