# Generated by Django 4.2.1 on 2023-05-18 06:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_delete_categoriemembre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='Annonces/images/')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementHemicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='EvenemenetsHemicycle/images/')),
            ],
        ),
        migrations.CreateModel(
            name='LoiAdoptee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='SymbolesAssemblee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='SymbolesAssemblee/images/')),
            ],
        ),
        migrations.CreateModel(
            name='TravauxCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('decription', tinymce.models.HTMLField()),
                ('commission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.categorie')),
            ],
        ),
    ]
