# Generated by Django 4.2.1 on 2023-05-18 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_annonce_evenementhemicycle_loiadoptee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementhemicycle',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
