# Generated by Django 4.2.1 on 2023-05-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_evenementhemicycle_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loiadoptee',
            name='content',
        ),
        migrations.AddField(
            model_name='loiadoptee',
            name='fichier',
            field=models.FileField(null=True, upload_to='LoisAdoptees/pdf/'),
        ),
    ]
