# Generated by Django 4.2.1 on 2023-05-18 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_loiadoptee_content_loiadoptee_fichier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenementhemicycle',
            old_name='date',
            new_name='dateDebut',
        ),
        migrations.AddField(
            model_name='evenementhemicycle',
            name='dateFin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
