# Generated by Django 4.2.1 on 2023-05-18 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_date_evenementhemicycle_datedebut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementhemicycle',
            name='heureDebut',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evenementhemicycle',
            name='heureFin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
