# Generated by Django 4.2.1 on 2023-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_evenementhemicycle_heuredebut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementhemicycle',
            name='lieu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
