# Generated by Django 4.2.1 on 2023-05-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_evenementhemicycle_lieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenementhemicycle',
            old_name='dateDebut',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='evenementhemicycle',
            name='dateFin',
        ),
    ]
