# Generated by Django 4.2.1 on 2023-05-18 14:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_datedebut_evenementhemicycle_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolesassemblee',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travauxcommission',
            name='decription',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
