# Generated by Django 4.2.1 on 2023-05-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_symbolesassemblee_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualitevideo',
            name='lien',
            field=models.FileField(null=True, upload_to='Actualites/videos/', verbose_name='Fichier de la video'),
        ),
    ]
