# Generated by Django 4.2.1 on 2023-05-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_loiadoptee_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(blank=True, null=True, upload_to='Galerie/photos/')),
            ],
        ),
    ]
