# Generated by Django 4.2.1 on 2023-05-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='loiadoptee',
            name='typeLoi',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
