# Generated by Django 4.2.1 on 2023-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_loiadoptee_typeloi'),
    ]

    operations = [
        migrations.AddField(
            model_name='travauxcommission',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='TravauxEnCommission/images/'),
        ),
    ]
