# Generated by Django 4.2.1 on 2023-05-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_rename_created_at_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
