# Generated by Django 4.2.1 on 2023-05-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depute',
            options={},
        ),
        migrations.AlterModelTable(
            name='depute',
            table='Depute',
        ),
    ]
