# Generated by Django 4.2.1 on 2023-05-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_depute_options_alter_depute_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='depute',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Depute/photos/', verbose_name='Photo du depute'),
        ),
    ]
