# Generated by Django 4.2.1 on 2023-05-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_depute_delete_utilisateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depute',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='depute',
            table=None,
        ),
    ]
