# Generated by Django 4.2.1 on 2023-05-17 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_categoriemembre'),
    ]

    operations = [
        migrations.AddField(
            model_name='depute',
            name='categorieMembre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comptes.categoriemembre'),
            preserve_default=False,
        ),
    ]
