# Generated by Django 4.2.1 on 2023-05-18 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0012_imageassociee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depute',
            name='categorieMembre',
        ),
        migrations.AddField(
            model_name='depute',
            name='categorie',
            field=models.CharField(blank=True, choices=[(0, 'Président'), (1, 'Membres du Bureau'), (2, 'Député'), (3, 'Anciens Présidents'), (4, 'Députés des précédentes législatures')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imageassociee',
            name='membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageassociee',
            name='source',
            field=models.ImageField(blank=True, null=True, upload_to='Membres/images/'),
        ),
        migrations.DeleteModel(
            name='categorieMembre',
        ),
    ]
