# Generated by Django 4.2.1 on 2023-05-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0013_remove_depute_categoriemembre_depute_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depute',
            name='categorie',
            field=models.CharField(blank=True, choices=[('PRESIDENT', 'Président'), ('MEMBRES_BUREAU', 'Membres du Bureau'), ('DEPUTE', 'Député'), ('ANCIENS_PRESIDENTS', 'Anciens Présidents'), ('DEPUTES_PRECEDENTES_LEGISLATURES', 'Députés des précédentes législatures')], max_length=100, null=True),
        ),
    ]
