# Generated by Django 4.2.1 on 2023-05-18 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0015_alter_depute_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='depute',
            name='enFonction',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='depute',
            name='precedentLegislature',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='ArticlePresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='President/articles/images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
