# Generated by Django 4.2.1 on 2023-05-18 16:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0016_depute_enfonction_depute_precedentlegislature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depute',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
