# Generated by Django 4.2.1 on 2023-05-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0018_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
