# Generated by Django 4.2.1 on 2023-05-18 22:24

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0019_delete_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='depute',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Membres/photos/'),
        ),
        migrations.AlterField(
            model_name='depute',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[60, 80], upload_to='Membres/picture_forum/'),
        ),
    ]
