# Generated by Django 4.2.1 on 2023-05-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0017_depute_bio'),
        ('comptes', '0020_depute_image_alter_depute_photo'),
    ]

    operations = [
    ]
