# Generated by Django 4.2.1 on 2023-05-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0021_merge_20230519_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depute',
            name='categorie',
            field=models.CharField(blank=True, choices=[('PRESIDENT', 'Président'), ('MEMBRE_BUREAU', 'Membre du Bureau'), ('DEPUTE', 'Député'), ('ANCIEN_PRESIDENT', 'Ancien Président'), ('DEPUTE_PRECEDENTE_LEGISLATURE', 'Député des précédentes législatures')], max_length=100, null=True),
        ),
    ]
